apiVersion: v1
kind: Pod
metadata:
  name: secure-02
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx:stable

      securityContext:
        allowPrivilegeEscalation: false
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop: ["ALL"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      emptyDir: {}
